[package]
name = "rust_ekf_engine-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
nalgebra = "0.32"

[dependencies.cellhawk-core]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_ekf"
path = "fuzz_targets/fuzz_ekf.rs"
test = false
doc = false
